# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20170828_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
