# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 22:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_course_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
