# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 03:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20170829_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='due_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
