# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 00:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_auto_20170831_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='owner',
        ),
    ]
