# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 00:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0014_entry_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='owner',
            new_name='user',
        ),
    ]
